### ISSUE TITLE
subclasses of EasyStalk::Job cannot be used as an Abstract Base Class

### ISSUE THREAD

**Issue by att14** [EasyPost/easy_stalk#29]
There appears to be a bug in the way this library does dependent tracking that does not allow subclasses of EasyStalk::Job to be inherited from.

**Comment by Roguelazer** [comment]
Hello friendos

This seems to still be the case?

**Comment by bkeyoumarsi** [comment]
it does indeed, we just hit this bug.

**Comment by bkeyoumarsi** [comment]
this was resolved in #17
